services:
  couchtube:
    image: ghcr.io/ozencb/couchtube:latest
    container_name: couchtube_app
    ports:
      - "8081:8081"  
    environment:
      - PORT=8081
      - DATABASE_FILE=/app/data/couchtube.db
      - READONLY_MODE=false
    volumes:
      - ./data:/app/data  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
