services:
  couchtube:
    image: ghcr.io/ozencb/couchtube:latest
    container_name: couchtube_app
    ports:
      - "8363:8363"  
    environment:
      - PORT=8363
      - DATABASE_FILE_PATH=/app/data/couchtube.db
      - JSON_FILE_PATH=/data/videos.json
      - READONLY_MODE=false
      - FULL_SCAN=true
    volumes:
      - couchtube_db:/app/data
      - ./videos.json:/app/data/videos.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8363"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  couchtube_db: