version: "3.8"

services:
  couchtube:
    image: ghcr.io/ozencb/couchtube:latest
    container_name: couchtube_app
    ports:
      - "8081:8081"
    environment:
      - PORT=8081                       # Example environment variable for custom configuration
    restart: unless-stopped
